// @flow

export const FETCH_GLOBAL_RATINGS         = 'FETCH_GLOBAL_RATINGS';
export const FETCH_GLOBAL_RATINGS_SUCCESS = 'FETCH_GLOBAL_RATINGS_SUCCESS';
export const FETCH_GLOBAL_RATINGS_ERROR   = 'FETCH_GLOBAL_RATINGS_ERROR';
