// @flow

export const FETCH_GOVERNANCES = 'governance/FETCH_GOVERNANCES';
export const FETCH_GOVERNANCES_SUCCESS = 'governance/FETCH_GOVERNANCES_SUCCESS';
export const FETCH_GOVERNANCES_FAILURE = 'governance/FETCH_GOVERNANCES_FAILURE';

export const CREATE_GOVERNANCE = 'governance/CREATE_GOVERNANCE';
export const CREATE_GOVERNANCE_SUCCESS = 'governance/CREATE_GOVERNANCE_SUCCESS';
export const CREATE_GOVERNANCE_FAILURE = 'governance/CREATE_GOVERNANCE_FAILURE';

export const DELETE_GOVERNANCE = 'governance/DELETE_GOVERNANCE';
export const DELETE_GOVERNANCE_SUCCESS = 'governance/DELETE_GOVERNANCE_SUCCESS';
export const DELETE_GOVERNANCE_FAILURE = 'governance/DELETE_GOVERNANCE_FAILURE';
export const DELETE_GOVERNANCE_LINKED_ERROR = 'governance/DELETE_GOVERNANCE_LINKED_ERROR';

export const UPDATE_GOVERNANCE = 'governance/UPDATE_GOVERNANCE';
export const UPDATE_GOVERNANCE_SUCCESS = 'governance/UPDATE_GOVERNANCE_SUCCESS';
export const UPDATE_GOVERNANCE_FAILURE = 'governance/UPDATE_GOVERNANCE_FAILURE';

export const CREATE_COMMITEE = 'governance/CREATE_COMMITEE';
export const CREATE_COMMITEE_SUCCESS = 'governance/CREATE_COMMITEE_SUCCESS';
export const CREATE_COMMITEE_FAILURE = 'governance/CREATE_COMMITEE_FAILURE';

export const DELETE_COMMITEE = 'governance/DELETE_COMMITEE';
export const DELETE_COMMITEE_SUCCESS = 'governance/DELETE_COMMITEE_SUCCESS';
export const DELETE_COMMITEE_FAILURE = 'governance/DELETE_COMMITEE_FAILURE';
export const DELETE_COMMITEE_LINKED_ERROR = 'governance/DELETE_COMMITEE_LINKED_ERROR';

export const UPDATE_COMMITEE = 'governance/UPDATE_COMMITEE';
export const UPDATE_COMMITEE_SUCCESS = 'governance/UPDATE_COMMITEE_SUCCESS';
export const UPDATE_COMMITEE_FAILURE = 'governance/UPDATE_COMMITEE_FAILURE';

export const CREATE_STATUS_INITIATIVE = 'governance/CREATE_STATUS_INITIATIVE';
export const CREATE_STATUS_INITIATIVE_SUCCESS = 'governance/CREATE_STATUS_INITIATIVE_SUCCESS';
export const CREATE_STATUS_INITIATIVE_FAILURE = 'governance/CREATE_STATUS_INITIATIVE_FAILURE';

export const DELETE_STATUS_INITIATIVE = 'governance/DELETE_STATUS_INITIATIVE';
export const DELETE_STATUS_INITIATIVE_SUCCESS = 'governance/DELETE_STATUS_INITIATIVE_SUCCESS';
export const DELETE_STATUS_INITIATIVE_FAILURE = 'governance/DELETE_STATUS_INITIATIVE_FAILURE';
export const DELETE_STATUS_LINKED_ERROR = 'governance/DELETE_STATUS_LINKED_ERROR';

export const UPDATE_STATUS_INITIATIVE = 'governance/UPDATE_STATUS_INITIATIVE';
export const UPDATE_STATUS_INITIATIVE_SUCCESS = 'governance/UPDATE_STATUS_INITIATIVE_SUCCESS';
export const UPDATE_STATUS_INITIATIVE_FAILURE = 'governance/UPDATE_STATUS_INITIATIVE_FAILURE';

export const CLEAR_GOVERNANCE_ERROR = 'governance/CLEAR_GOVERNANCE_ERROR';
